### ISSUE TITLE
Discutir sobre quando acaba um jogo

### ISSUE THREAD

**Issue by AHVG** [AHVG/INE5417#8]
O que o player vai poder fazer ao fim de jogo

**Comment by AHVG** [comment]
Vai aparecer um botão para começar um novo match (restart) quando terminar ou ele vai ficar na barra superior todo o jogo?

**Comment by Diego-Azevedo** [comment]
poderia aparecer um banner indicando a vitória, com um botão de jogar novamente e outro botão de sair.

**Comment by BrenoSPXx** [comment]
Concordo com o Diego
